// ? Project: Aero Search
// ? File: CreativeModeInventoryScreenMixin.java
// ? Directory: /src/main/java/gg/theexiles/aerosearch/mixin
// ? Description: Patches the native Creative Search tab and draws advanced-search suggestions/help.
// ? Created by: Watty
// ? Created on: 2026-08-07 14:16 EDT
// ? Last modified by: Watty
// ? Last modified on: 2026-08-07 15:12 EDT

package gg.theexiles.aerosearch.mixin;
import gg.theexiles.aerosearch.index.SearchIndex; import gg.theexiles.aerosearch.search.*; import gg.theexiles.aerosearch.ui.*; import net.minecraft.client.Minecraft; import net.minecraft.client.gui.GuiGraphics; import net.minecraft.client.gui.components.EditBox; import net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen; import net.minecraft.world.inventory.Slot; import net.minecraft.world.item.CreativeModeTab; import net.minecraft.world.item.CreativeModeTabs; import org.lwjgl.glfw.GLFW; import org.spongepowered.asm.mixin.*; import org.spongepowered.asm.mixin.injection.*; import org.spongepowered.asm.mixin.injection.callback.*; import java.util.List;
@Mixin(CreativeModeInventoryScreen.class)
public abstract class CreativeModeInventoryScreenMixin {
 @Shadow private EditBox searchBox; @Shadow private static CreativeModeTab selectedTab; @Unique private String aerosearch$lastQuery="";
 @Inject(method="refreshSearchResults",at=@At("HEAD"),cancellable=true) private void aerosearch$refresh(CallbackInfo ci){CreativeModeInventoryScreen self=(CreativeModeInventoryScreen)(Object)this;if(searchBox==null||selectedTab!=CreativeModeTabs.searchTab())return;String q=searchBox.getValue();if(q==null||q.isBlank())return;var menu=self.getMenu();menu.items.clear();SearchEngine.search(q).forEach(d->menu.items.add(d.stack().copy()));menu.scrollTo(0);aerosearch$lastQuery=q;SearchSession.remember(q);ci.cancel();}
 @Inject(method="render",at=@At("TAIL")) private void aerosearch$render(GuiGraphics g,int mx,int my,float pt,CallbackInfo ci){if(searchBox==null||selectedTab!=CreativeModeTabs.searchTab()||!SearchSession.help())return;Minecraft mc=Minecraft.getInstance();List<String>s=SuggestionEngine.suggest(searchBox.getValue(),6);int x=searchBox.getX(),y=searchBox.getY()+searchBox.getHeight()+3;if(SearchIndex.isRebuilding()){g.drawString(mc.font,"Aero Search: indexing…",x,y,0xFFE6C54A,true);y+=10;}for(String a:s){g.fill(x-2,y-1,x+Math.min(220,mc.font.width(a)+8),y+9,0xB0101010);g.drawString(mc.font,a,x+2,y,0xFFE9F7FF,false);y+=10;}if(!SearchSession.palette().isEmpty())g.drawString(mc.font,"Palette seeds: "+SearchSession.palette().size(),x,y+2,0xFF59D9E8,true);}
 @Inject(method="keyPressed",at=@At("HEAD"),cancellable=true) private void aerosearch$key(int key,int scan,int mods,CallbackInfoReturnable<Boolean> cir){if(searchBox==null||!searchBox.isFocused())return;if((mods&GLFW.GLFW_MOD_CONTROL)!=0&&key==GLFW.GLFW_KEY_SPACE){List<String>s=SuggestionEngine.suggest(searchBox.getValue(),1);if(!s.isEmpty()){String c=searchBox.getValue();int p=c.lastIndexOf(' ');searchBox.setValue((p<0?"":c.substring(0,p+1))+s.get(0));cir.setReturnValue(true);}}}
 @Inject(method="mouseClicked",at=@At("HEAD")) private void aerosearch$mouse(double x,double y,int button,CallbackInfoReturnable<Boolean> cir){if(button!=GLFW.GLFW_MOUSE_BUTTON_MIDDLE)return;CreativeModeInventoryScreen self=(CreativeModeInventoryScreen)(Object)this;Slot slot=self.getSlotUnderMouse();if(slot==null||!slot.hasItem())return;var id=net.minecraft.core.registries.BuiltInRegistries.ITEM.getKey(slot.getItem().getItem());if(id==null)return;long w=Minecraft.getInstance().getWindow().getWindow();boolean shift=GLFW.glfwGetKey(w,GLFW.GLFW_KEY_LEFT_SHIFT)==GLFW.GLFW_PRESS||GLFW.glfwGetKey(w,GLFW.GLFW_KEY_RIGHT_SHIFT)==GLFW.GLFW_PRESS;if(shift)SearchSession.togglePalette(id.toString());else if(searchBox!=null)searchBox.setValue("similar:"+id);LearningStore.record(aerosearch$lastQuery,id.toString());}
}
