modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="exsearch"
version="${mod_version}"
displayName="ExSearch"
authors="Watty"
description='''Builder-first semantic, color, visual, and JEI-style search for the Minecraft Creative inventory.'''
displayTest="IGNORE_ALL_VERSION"

[[dependencies.exsearch]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.exsearch]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="CLIENT"

[[mixins]]
config="aerosearch.mixins.json"
