// ? Project: Aero Search
// ? File: SearchEngine.java
// ? Directory: /src/main/java/gg/theexiles/aerosearch/search
// ? Description: Filter evaluation, fuzzy ranking, semantic search, similarity and palette scoring.
// ? Created by: Watty
// ? Created on: 2026-08-07 14:16 EDT
// ? Last modified by: Watty
// ? Last modified on: 2026-08-07 14:16 EDT

package gg.theexiles.aerosearch.search;
import gg.theexiles.aerosearch.color.ColorMath; import gg.theexiles.aerosearch.index.SearchIndex; import gg.theexiles.aerosearch.model.SearchDocument; import gg.theexiles.aerosearch.query.*; import java.util.*;
public final class SearchEngine {
 public static final int RESULT_CAP=5000; private SearchEngine(){}
 public static List<SearchDocument> search(String raw){Query q=QueryParser.parse(raw);List<SearchDocument> docs=SearchIndex.documents();if(raw==null||raw.isBlank())return docs;Map<String,SearchDocument> by=new HashMap<>();for(SearchDocument d:docs)by.put(d.id(),d);SearchDocument sim=q.similarTo==null?null:by.get(q.similarTo);List<SearchDocument> palette=q.paletteSeeds.stream().map(by::get).filter(Objects::nonNull).toList();List<Scored> out=new ArrayList<>();for(SearchDocument d:docs){if(!all(d,q.terms)||anyMatch(d,q.excluded))continue;double s=base(d,q.terms)*d.rankBoost();if(sim!=null)s+=similarity(sim,d)*3;if(!palette.isEmpty())s+=palette(palette,d)*2.4;s+=LearningStore.boost(raw,d.id());out.add(new Scored(d,s));}out.sort(Comparator.comparingDouble(Scored::score).reversed().thenComparing(x->x.doc().displayName(),String.CASE_INSENSITIVE_ORDER));return out.stream().limit(RESULT_CAP).map(Scored::doc).toList();}
 private static boolean all(SearchDocument d,List<Query.Term> t){for(var x:t)if(!match(d,x))return false;return true;} private static boolean anyMatch(SearchDocument d,List<Query.Term> t){for(var x:t)if(match(d,x))return true;return false;}
 private static boolean match(SearchDocument d,Query.Term t){String v=t.value().toLowerCase(Locale.ROOT);return switch(t.type()){case TEXT->text(d,v)>=.45;case MOD->contains(d.namespace(),v)||contains(d.modName(),v);case TAG->d.tags().stream().anyMatch(x->contains(x,v));case TOOLTIP->d.tooltips().stream().anyMatch(x->contains(x,v));case ID->contains(d.id(),v);case NUMERIC->switch(t.key()){case"light"->t.comparison().test(d.light());case"hardness"->t.comparison().test(d.hardness());case"blast"->t.comparison().test(d.blastResistance());default->false;};case FILTER->filter(d,t.key(),v);};}
 private static boolean filter(SearchDocument d,String k,String v){return switch(k){case"mod"->contains(d.namespace(),v)||contains(d.modName(),v);case"tag"->d.tags().stream().anyMatch(x->contains(x,v));case"tooltip"->d.tooltips().stream().anyMatch(x->contains(x,v));case"id"->contains(d.id(),v);case"material"->set(d.materials(),v);case"shape"->set(d.shapes(),v);case"use"->set(d.uses(),v);case"style"->set(d.styles(),v);case"color"->color(d,v);case"transparent"->bool(v,d.transparent());case"waterloggable"->bool(v,d.waterloggable());case"redstone"->bool(v,d.redstone());case"fullblock"->bool(v,d.fullBlock());case"slab"->bool(v,d.slab());case"stairs"->bool(v,d.stairs());case"wall"->bool(v,d.wall());case"animated"->bool(v,d.animated());case"emissive"->bool(v,d.emissive());case"source"->v.equals("vanilla")?d.namespace().equals("minecraft"):v.equals("modded")?!d.namespace().equals("minecraft"):contains(d.namespace(),v);default->text(d,k+" "+v)>=.52;};}
 private static boolean color(SearchDocument d,String v){try{int t=ColorMath.parseColor(v);return t>=0&&Math.min(ColorMath.distance(t,d.color().primaryRgb()),ColorMath.distance(t,d.color().secondaryRgb()))<=28;}catch(RuntimeException e){return false;}}
 private static double base(SearchDocument d,List<Query.Term> terms){if(terms.isEmpty())return 1;double s=0;for(var t:terms)s+=t.type()==Query.Term.Type.TEXT?text(d,t.value()):1;return s/terms.size();}
 private static double text(SearchDocument d,String q){double b=Math.max(Fuzzy.score(q,d.displayName()),Fuzzy.score(q,d.path()));b=Math.max(b,Fuzzy.score(q,d.id())*.95);b=Math.max(b,Fuzzy.score(q,d.modName())*.72);for(String x:d.keywords())b=Math.max(b,Fuzzy.score(q,x)*.92);for(String x:d.materials())b=Math.max(b,Fuzzy.score(q,x)*.86);for(String x:d.shapes())b=Math.max(b,Fuzzy.score(q,x)*.86);for(String x:d.uses())b=Math.max(b,Fuzzy.score(q,x)*.86);for(String x:d.styles())b=Math.max(b,Fuzzy.score(q,x)*.86);return b;}
 private static double similarity(SearchDocument a,SearchDocument b){if(a.id().equals(b.id()))return-100;double c=1-Math.min(1,Math.min(ColorMath.distance(a.color().primaryRgb(),b.color().primaryRgb()),ColorMath.distance(a.color().primaryRgb(),b.color().secondaryRgb()))/70);double sem=jacc(union(a.materials(),a.shapes(),a.uses(),a.styles()),union(b.materials(),b.shapes(),b.uses(),b.styles()));double p=(a.fullBlock()==b.fullBlock()?.2:0)+(a.transparent()==b.transparent()?.1:0)+(a.emissive()==b.emissive()?.1:0);return c*.58+sem*.32+p;}
 private static double palette(List<SearchDocument>s,SearchDocument c){if(s.stream().anyMatch(x->x.id().equals(c.id())))return-100;double t=0;for(SearchDocument x:s){double d=ColorMath.distance(x.color().primaryRgb(),c.color().primaryRgb()),col=d<18?.8:d>45&&d<85?1:.45;t+=col*.45+jacc(x.styles(),c.styles())*.25+jacc(x.uses(),c.uses())*.15+jacc(x.materials(),c.materials())*.15;}return t/Math.max(1,s.size());}
 private static boolean set(Set<String>s,String q){return s.stream().anyMatch(x->contains(x,q));} private static boolean contains(String v,String q){return v!=null&&v.toLowerCase(Locale.ROOT).contains(q.toLowerCase(Locale.ROOT));} private static boolean bool(String r,boolean v){return switch(r){case"true","yes","1","on"->v;case"false","no","0","off"->!v;default->false;};}
 @SafeVarargs private static Set<String> union(Set<String>...s){Set<String>o=new HashSet<>();for(Set<String>x:s)o.addAll(x);return o;} private static double jacc(Set<String>a,Set<String>b){if(a.isEmpty()&&b.isEmpty())return 0;Set<String>i=new HashSet<>(a);i.retainAll(b);Set<String>u=new HashSet<>(a);u.addAll(b);return i.size()/(double)Math.max(1,u.size());} private record Scored(SearchDocument doc,double score){}
}
